#!/usr/bin/env python3
"""Generate Vocs MDX API reference from sent source code."""

from __future__ import annotations

import json
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = DOCS_DIR.parent
PAGES_DIR = DOCS_DIR / "src" / "pages"
GENERATED_DIR = DOCS_DIR / "generated"

sys.path.insert(0, str(DOCS_DIR / "scripts"))
from ast_utils import (  # noqa: E402
    ClassInfo,
    MethodInfo,
    format_signature,
    mdx_method_section,
    parse_module,
    slugify,
)

CLIENT_SECTIONS = {
    "connection": {
        "title": "Connection",
        "files": ["telegrambaseclient.py", "telegramclient.py"],
        "methods": {
            "TelegramBaseClient": [
                "__init__",
                "connect",
                "disconnect",
                "is_connected",
                "__call__",
                "__aenter__",
                "__aexit__",
            ],
            "TelegramClient": ["__init__", "start"],
        },
    },
    "auth": {
        "title": "Authentication",
        "files": ["auth.py"],
        "class": "AuthMethods",
    },
    "messages": {
        "title": "Messages",
        "files": ["messages.py"],
        "class": "MessageMethods",
    },
    "files": {
        "title": "Files",
        "files": ["uploads.py", "downloads.py"],
        "classes": ["UploadMethods", "DownloadMethods"],
    },
    "users": {
        "title": "Users",
        "files": ["users.py"],
        "class": "UserMethods",
    },
    "chats": {
        "title": "Chats",
        "files": ["chats.py"],
        "class": "ChatMethods",
    },
    "dialogs": {
        "title": "Dialogs",
        "files": ["dialogs.py"],
        "class": "DialogMethods",
    },
    "bots": {
        "title": "Bots",
        "files": ["bots.py"],
        "class": "BotMethods",
    },
    "updates": {
        "title": "Updates & Events",
        "files": ["updates.py"],
        "class": "UpdateMethods",
    },
}

METHOD_EXAMPLES = {
    "start": """await client.start()
await client.start(bot_token=BOT_TOKEN)
await client.start(phone=PHONE, code=CODE)""",
    "connect": "await client.connect()",
    "send_message": 'await client.send_message("username", "Hello!")',
    "get_entity": 'user = await client.get_entity("username")',
    "iter_messages": """async for message in client.iter_messages("channel"):
    print(message.text)""",
    "on": """@client.on(events.NewMessage)
async def handler(event):
    await event.reply("Hi!")""",
    "send_file": 'await client.send_file("username", "photo.jpg", caption="Check this out")',
    "download_media": 'path = await client.download_media(message, "downloads/")',
    "get_me": "me = await client.get_me()",
    "conversation": """async with client.conversation("username") as conv:
    await conv.send_message("What's your name?")
    response = await conv.get_response()""",
}

TL_METHOD_MAP = {
    "send_message": ("functions.messages", "MessagesSendMessage"),
    "edit_message": ("functions.messages", "MessagesEditMessage"),
    "delete_messages": ("functions.messages", "MessagesDeleteMessages"),
    "get_dialogs": ("functions.messages", "MessagesGetDialogs"),
    "get_entity": ("functions.users", "UsersGetUsers"),
    "send_file": ("functions.messages", "MessagesSendMedia"),
    "download_media": ("functions.upload", "UploadGetFile"),
    "sign_in": ("functions.auth", "AuthSignIn"),
    "send_code_request": ("functions.auth", "AuthSendCode"),
}

EVENT_FILES = [
    "newmessage.py",
    "messageedited.py",
    "messagedeleted.py",
    "messageread.py",
    "callbackquery.py",
    "inlinequery.py",
    "chataction.py",
    "raw.py",
    "userupdate.py",
    "album.py",
]

GENERATED_BANNER = "{/* Auto-generated by docs/scripts/generate_docs.py. Do not edit manually. */}\n\n"


def _client_dir() -> Path:
    return REPO_ROOT / "sent" / "client"


def _events_dir() -> Path:
    return REPO_ROOT / "sent" / "events"


def _sessions_dir() -> Path:
    return REPO_ROOT / "sent" / "sessions"


def _errors_dir() -> Path:
    return REPO_ROOT / "sent" / "errors"


def _tl_types_dir() -> Path:
    return REPO_ROOT / "sent" / "tl" / "types"


def _tl_functions_dir() -> Path:
    return REPO_ROOT / "sent" / "tl" / "functions"


def _find_class(classes: list[ClassInfo], name: str) -> ClassInfo | None:
    for c in classes:
        if c.name == name:
            return c
    return None


def _methods_for_class(path: Path, class_name: str) -> list[MethodInfo]:
    cls = _find_class(parse_module(path), class_name)
    if not cls:
        return []
    return [m for m in cls.methods if not m.name.startswith("_") or m.name in ("__call__",)]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED_BANNER + content, encoding="utf-8")


def _tl_link(method_name: str) -> str:
    if method_name not in TL_METHOD_MAP:
        return ""
    ns, cls = TL_METHOD_MAP[method_name]
    kind = ns.split(".")[-1]
    return f"\n\n**Underlying TL:** [`{cls}`](/tl/{kind}/{ns.split('.')[-1] if kind == 'functions' else kind}#{cls.lower()})"


def generate_client_section(section_id: str, config: dict) -> str:
    lines = [f"# {config['title']}", ""]
    all_methods: list[MethodInfo] = []

    if "methods" in config:
        for fname in config["files"]:
            path = _client_dir() / fname
            classes = parse_module(path)
            for cls_name, method_names in config["methods"].items():
                cls = _find_class(classes, cls_name)
                if not cls:
                    continue
                for m in cls.methods:
                    if m.name in method_names:
                        all_methods.append(m)
    elif "classes" in config:
        for fname in config["files"]:
            path = _client_dir() / fname
            classes = parse_module(path)
            for cls_name in config["classes"]:
                all_methods.extend(_methods_for_class(path, cls_name))
    else:
        fname = config["files"][0]
        path = _client_dir() / fname
        all_methods = _methods_for_class(path, config["class"])

    for method in all_methods:
        example = METHOD_EXAMPLES.get(method.name, "")
        lines.append(mdx_method_section(method, example))
        if method.name in TL_METHOD_MAP:
            ns, tl_cls = TL_METHOD_MAP[method.name]
            kind = "functions" if "functions" in ns else "types"
            ns_name = ns.split(".")[-1]
            lines.append(f"**Underlying TL:** [`{tl_cls}`](/tl/{kind}/{ns_name}#{tl_cls.lower()})")
            lines.append("")

    return "\n".join(lines)


def generate_client_index() -> str:
    return """# TelegramClient

`TelegramClient` is the main entry point for **sent**. It combines connection management, authentication, messaging, file transfer, entity resolution, chat management, bot helpers, and event handling.

## Class hierarchy

```
TelegramClient
├── TelegramBaseClient   (connection, RPC)
├── AuthMethods          (login, 2FA, QR)
├── MessageMethods       (send, edit, forward, polls)
├── UploadMethods        (upload_file, send_file)
├── DownloadMethods      (download_media, profile photos)
├── UserMethods          (get_entity, get_me)
├── ChatMethods          (channels, groups, permissions)
├── DialogMethods        (get_dialogs, iter_dialogs)
├── BotMethods           (callbacks, inline queries)
└── UpdateMethods        (event handlers, catch_up)
```

## Quick example

```python
import asyncio
from sent import TelegramClient, events

async def main():
    async with TelegramClient("session", API_ID, API_HASH) as client:
        await client.start()

        @client.on(events.NewMessage)
        async def handler(event):
            await event.reply("Hello!")

        await client.run_until_disconnected()

asyncio.run(main())
```

## Sections

| Section | Description |
|---------|-------------|
| [Connection](/api/client/connection) | `connect`, `disconnect`, raw RPC |
| [Authentication](/api/client/auth) | Login, 2FA, bot token, QR |
| [Messages](/api/client/messages) | Send, edit, forward, polls, reactions |
| [Files](/api/client/files) | Upload and download media |
| [Users](/api/client/users) | Entity resolution and profiles |
| [Chats](/api/client/chats) | Channels, groups, permissions |
| [Dialogs](/api/client/dialogs) | List conversations |
| [Bots](/api/client/bots) | Callback and inline query answers |
| [Updates & Events](/api/client/updates) | Handler registration |
"""


def generate_events() -> tuple[str, list[dict]]:
    index_lines = [
        "# Events",
        "",
        "Register handlers with `@client.on(...)` or `client.add_event_handler(...)`.",
        "",
        "## Event builders",
        "",
        "| Builder | Description |",
        "|---------|-------------|",
    ]
    sidebar_items = [{"text": "Overview", "link": "/api/events"}]
    pages: list[tuple[str, str]] = []

    descriptions = {
        "NewMessage": "Fired when a new message is sent or received.",
        "MessageEdited": "Fired when a message is edited.",
        "MessageDeleted": "Fired when messages are deleted.",
        "MessageRead": "Fired when messages are marked as read.",
        "CallbackQuery": "Fired when an inline keyboard button is pressed.",
        "InlineQuery": "Fired when a bot receives an inline query.",
        "ChatAction": "Fired on join, leave, title change, and similar actions.",
        "Raw": "Receives unfiltered raw TL updates.",
        "UserUpdate": "Fired on user status, name, or typing changes.",
        "Album": "Groups media sent as an album into one event.",
    }

    for fname in EVENT_FILES:
        path = _events_dir() / fname
        classes = parse_module(path)
        builders = [c for c in classes if c.name not in ("EventCommon", "EventBuilder") and not c.name.endswith("Event")]
        for builder in builders:
            slug = slugify(builder.name)
            desc = descriptions.get(builder.name, builder.docstring or "")
            index_lines.append(f"| [`{builder.name}`](/api/events/{slug}) | {desc} |")
            sidebar_items.append({"text": builder.name, "link": f"/api/events/{slug}"})

            page = [f"# {builder.name}", "", desc, ""]
            init_method = next((m for m in builder.methods if m.name == "__init__"), None)
            if init_method:
                page.append("## Filters")
                page.append("")
                page.append(mdx_method_section(init_method))
            event_cls = next(
                (c for c in classes if c.name == f"{builder.name}Event"),
                None,
            )
            if event_cls:
                page.extend(["## Event instance", ""])
                for m in event_cls.methods:
                    if not m.name.startswith("_"):
                        page.append(mdx_method_section(m))
                for slot in event_cls.slots:
                    page.append(f"- `{slot}`")
                page.append("")
            elif builder.name == "Album":
                page.extend(
                    [
                        "## Event instance",
                        "",
                        "Returns a list of [`MessageEvent`](/api/events/newmessage) objects for grouped media.",
                        "",
                    ]
                )
            pages.append((slug, "\n".join(page)))

    common = parse_module(_events_dir() / "common.py")
    eb = _find_class(common, "EventBuilder")
    if eb:
        init = next((m for m in eb.methods if m.name == "__init__"), None)
        if init:
            index_lines.extend(["", "## Common filters (`EventBuilder`)", ""])
            index_lines.append(mdx_method_section(init))

    index_lines.extend(
        [
            "",
            "## Registration",
            "",
            "```python",
            "@client.on(events.NewMessage(incoming=True, pattern=r'hello'))",
            "async def handler(event):",
            "    await event.reply('Hi!')",
            "",
            "await client.run_until_disconnected()",
            "```",
        ]
    )

    return "\n".join(index_lines), sidebar_items, pages


def generate_sessions() -> str:
    lines = [
        "# Sessions",
        "",
        "Sessions store the authorization key, datacenter, entity cache, and update state.",
        "",
        "| Class | Description |",
        "|-------|-------------|",
        "| `SQLiteSession` | Default file-backed session (`name.session`) |",
        "| `StringSession` | Portable base64 string (starts with `1`) |",
        "| `MemorySession` | In-memory, not persisted |",
        "| `Session` | Abstract base for custom implementations |",
        "",
    ]
    for fname in ["abstract.py", "sqlite.py", "string.py", "memory.py"]:
        path = _sessions_dir() / fname
        for cls in parse_module(path):
            lines.extend([f"## `{cls.name}`", ""])
            if cls.docstring:
                lines.append(cls.docstring)
                lines.append("")
            if cls.bases:
                lines.append(f"**Bases:** `{', '.join(cls.bases)}`")
                lines.append("")
            for m in cls.methods:
                if m.name.startswith("_"):
                    continue
                lines.append(mdx_method_section(m))
    return "\n".join(lines)


def generate_errors() -> str:
    lines = [
        "# Errors",
        "",
        "All sent exceptions inherit from `SentError`. RPC errors inherit from `RPCError`.",
        "",
        "## Hierarchy",
        "",
        "```",
        "SentError",
        "├── AuthKeyError",
        "│   └── AuthKeyUnregisteredError",
        "├── SessionPasswordNeededError",
        "└── RPCError",
        "    ├── FloodWaitError",
        "    ├── PhoneCodeInvalidError",
        "    └── ... (see below)",
        "```",
        "",
        "## Exception reference",
        "",
    ]
    for fname in ["common.py", "rpcerrorlist.py"]:
        path = _errors_dir() / fname
        for cls in parse_module(path):
            if cls.name == "SentError":
                continue
            desc = cls.docstring or "Telegram RPC error."
            lines.extend([f"### `{cls.name}`", "", desc, ""])
            init = next((m for m in cls.methods if m.name == "__init__"), None)
            if init and len(init.params) > 1:
                lines.append(mdx_method_section(init))
    lines.extend(
        [
            "## Handling flood waits",
            "",
            "```python",
            "from sent.errors import FloodWaitError",
            "",
            "try:",
            "    await client.send_message(chat, text)",
            "except FloodWaitError as e:",
            "    await asyncio.sleep(e.seconds)",
            "```",
            "",
            "Set `flood_sleep_threshold` on the client to auto-sleep for short waits.",
        ]
    )
    return "\n".join(lines)


def generate_helpers() -> tuple[str, str]:
    button_path = _client_dir() / "buttons.py"
    conv_path = _client_dir() / "conversation.py"

    button_lines = ["# Button", "", "Build inline and reply keyboards.", ""]
    for cls in parse_module(button_path):
        if cls.name == "Button":
            for m in cls.methods:
                if not m.name.startswith("_"):
                    button_lines.append(mdx_method_section(m))

    button_lines.extend(
        [
            "## Example",
            "",
            "```python",
            "from sent.client.buttons import Button",
            "",
            "buttons = Button.build([",
            "    [Button.inline('Yes', data=b'yes'), Button.inline('No', data=b'no')],",
            "])",
            "await client.send_message(chat, 'Confirm?', buttons=buttons)",
            "```",
        ]
    )

    conv_lines = ["# Conversation", "", "Wait for replies in a chat.", ""]
    for cls in parse_module(conv_path):
        if cls.name == "Conversation":
            if cls.docstring:
                conv_lines.extend([cls.docstring, ""])
            for m in cls.methods:
                if not m.name.startswith("_") or m.name in ("__aenter__", "__aexit__"):
                    example = METHOD_EXAMPLES.get("conversation", "") if m.name == "__aenter__" else ""
                    conv_lines.append(mdx_method_section(m, example))

    return "\n".join(button_lines), "\n".join(conv_lines)


def generate_tl_namespace(kind: str, path: Path, namespace: str) -> str:
    import_path = f"sent.tl.{kind}.{namespace}"
    title = f"TL {'Types' if kind == 'types' else 'Functions'}: `{namespace}`"
    lines = [f"# {title}", "", f"Import from `{import_path}`.", "", "## Contents", ""]
    classes = parse_module(path)
    for cls in classes:
        if cls.name.startswith("_"):
            continue
        anchor = cls.name.lower()
        lines.append(f"- [{cls.name}](#{anchor})")
    lines.append("")

    for cls in classes:
        if cls.name.startswith("_"):
            continue
        lines.extend([f"## {cls.name}", ""])
        if cls.constructor_id is not None:
            lines.append(f"**Constructor ID:** `{cls.constructor_id}`")
            lines.append("")
        if cls.slots:
            lines.append(f"**Fields:** `{', '.join(f'`{s}`' for s in cls.slots)}`")
            lines.append("")
        init = next((m for m in cls.methods if m.name == "__init__"), None)
        if init:
            lines.append("```python")
            lines.append(format_signature(init, prefix=f"{cls.name}."))
            lines.append("```")
            lines.append("")
            lines.append(params_table_simple(init))
            lines.append("")
        lines.extend(
            [
                "```python",
                f"from {import_path} import {cls.name}",
                "```",
                "",
            ]
        )
        if kind == "functions":
            lines.extend(
                [
                    "```python",
                    f"result = await client({cls.name}(...))",
                    "```",
                    "",
                ]
            )
    return "\n".join(lines)


def params_table_simple(method: MethodInfo) -> str:
    from ast_utils import params_table

    return params_table(method)


def generate_sidebar(
    tl_type_ns: list[str],
    tl_func_ns: list[str],
    event_items: list[dict],
) -> dict:
    return {
        "apiReference": {
            "text": "API Reference",
            "items": [
                {
                    "text": "TelegramClient",
                    "items": [
                        {"text": "Overview", "link": "/api/client"},
                        {"text": "Connection", "link": "/api/client/connection"},
                        {"text": "Authentication", "link": "/api/client/auth"},
                        {"text": "Messages", "link": "/api/client/messages"},
                        {"text": "Files", "link": "/api/client/files"},
                        {"text": "Users", "link": "/api/client/users"},
                        {"text": "Chats", "link": "/api/client/chats"},
                        {"text": "Dialogs", "link": "/api/client/dialogs"},
                        {"text": "Bots", "link": "/api/client/bots"},
                        {"text": "Updates & Events", "link": "/api/client/updates"},
                    ],
                },
                {"text": "Events", "items": event_items},
                {"text": "Sessions", "link": "/api/sessions"},
                {"text": "Errors", "link": "/api/errors"},
                {
                    "text": "Helpers",
                    "items": [
                        {"text": "Button", "link": "/api/helpers/button"},
                        {"text": "Conversation", "link": "/api/helpers/conversation"},
                    ],
                },
            ],
        },
        "tlReference": {
            "text": "TL Reference",
            "items": [
                {"text": "Overview", "link": "/tl"},
                {
                    "text": "Types",
                    "items": [
                        {"text": ns if ns != "mtproto" else "mtproto (core)", "link": f"/tl/types/{ns}"}
                        for ns in sorted(tl_type_ns)
                    ],
                },
                {
                    "text": "Functions",
                    "items": [{"text": ns, "link": f"/tl/functions/{ns}"} for ns in sorted(tl_func_ns)],
                },
            ],
        },
    }


def main() -> None:
    print("Generating sent API documentation...")

    # Client API
    client_dir = PAGES_DIR / "api" / "client"
    _write(client_dir / "index.mdx", generate_client_index())
    for section_id, config in CLIENT_SECTIONS.items():
        _write(client_dir / f"{section_id}.mdx", generate_client_section(section_id, config))
    print(f"  Client API: {len(CLIENT_SECTIONS) + 1} pages")

    # Events
    events_index, event_sidebar, event_pages = generate_events()
    events_dir = PAGES_DIR / "api" / "events"
    _write(events_dir / "index.mdx", events_index)
    for slug, content in event_pages:
        _write(events_dir / f"{slug}.mdx", content)
    print(f"  Events: {1 + len(event_pages)} pages")

    # Sessions & Errors
    _write(PAGES_DIR / "api" / "sessions.mdx", generate_sessions())
    _write(PAGES_DIR / "api" / "errors.mdx", generate_errors())
    button_mdx, conv_mdx = generate_helpers()
    _write(PAGES_DIR / "api" / "helpers" / "button.mdx", button_mdx)
    _write(PAGES_DIR / "api" / "helpers" / "conversation.mdx", conv_mdx)
    print("  Sessions, Errors, Helpers: 4 pages")

    # TL reference
    tl_types_dir = PAGES_DIR / "tl" / "types"
    tl_funcs_dir = PAGES_DIR / "tl" / "functions"
    tl_type_ns: list[str] = []
    tl_func_ns: list[str] = []

    for path in sorted(_tl_types_dir().glob("*.py")):
        if path.name in ("__init__.py", "all.py"):
            continue
        ns = path.stem
        tl_type_ns.append(ns)
        _write(tl_types_dir / f"{ns}.mdx", generate_tl_namespace("types", path, ns))
    all_path = _tl_types_dir() / "all.py"
    if all_path.exists():
        _write(tl_types_dir / "mtproto.mdx", generate_tl_namespace("types", all_path, "all"))
        tl_type_ns.append("mtproto")

    for path in sorted(_tl_functions_dir().glob("*.py")):
        if path.name in ("__init__.py", "all.py"):
            continue
        ns = path.stem
        tl_func_ns.append(ns)
        _write(tl_funcs_dir / f"{ns}.mdx", generate_tl_namespace("functions", path, ns))

    all_func = _tl_functions_dir() / "all.py"
    if all_func.exists():
        tl_func_ns.append("mtproto")
        _write(tl_funcs_dir / "mtproto.mdx", generate_tl_namespace("functions", all_func, "all"))

    print(f"  TL types: {len(tl_type_ns)} namespaces")
    print(f"  TL functions: {len(tl_func_ns)} namespaces")

    # Sidebar
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    sidebar = generate_sidebar(tl_type_ns, tl_func_ns, event_sidebar)
    (GENERATED_DIR / "sidebar.json").write_text(json.dumps(sidebar, indent=2), encoding="utf-8")
    print("  sidebar.json written")
    print("Done.")


if __name__ == "__main__":
    main()
